removed node-sass as un-used dependency as reported by depcheck and also as dart sass superseded node-sas and is already listed in package.json
Last login: Thu Jul 28 16:58:44 on ttys002

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
UK-C02FXE9CMD6M:ccd-data-store-api dineshpatel$ cd ..
UK-C02FXE9CMD6M:CCD_Projects dineshpatel$ cd ..
UK-C02FXE9CMD6M:Sandbox dineshpatel$ cls

UK-C02FXE9CMD6M:Sandbox dineshpatel$ ls
BackUpFortify_ScanCentral_Client_Latest_x64learn-terraform-provision-eks-cluster
Before MergingFunctionalInterfacesresource-planner-api
CCD_ProjectsJava_Dev_Projectsresource-planner-fe
DevOPSTest_CCD_Projectsresource-planner-kubernetes
Fortifygithub-recovery-codes.txtresourceplanner.p12
UK-C02FXE9CMD6M:Sandbox dineshpatel$ cd CCD_Projects/
UK-C02FXE9CMD6M:CCD_Projects dineshpatel$ ls
PostgreSQL_Scriptsccd-case-document-am-apiccd-test-stubs-servicegithub-management
PostgressCommandsccd-case-management-webccd-user-profile-apigithub-slack-user-mappings
aac-manage-case-assignmentccd-case-print-servicecnp-flux-confighmc-cft-hearing-service
ccd-admin-webccd-data-store-apicnp-flux-config_oldhmc-hmi-inbound-adapter
ccd-api-gatewayccd-definition-store-apicpo-case-payment-orders-apitest_repo1
ccd-case-activity-apiccd-dockerdevops-azure-adts-translation-service
ccd-case-disposerccd-message-publisherfortify-clientwa-post-deployment-ft-tests
UK-C02FXE9CMD6M:CCD_Projects dineshpatel$ cd ccd-docker/
UK-C02FXE9CMD6M:ccd-docker dineshpatel$ git status
On branch master
Your branch is up to date with origin/master.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
modified:   bin/add-role-assignments.sh
modified:   bin/am-role-assignments.json
modified:   bin/ccd-roles.json
modified:   bin/env_variables_all.txt
modified:   bin/users.json
modified:   bin/utils/idam-get-user.sh
modified:   bulk-user-setup/sample_test.csv
modified:   compose/frontend.yml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
.DS_Store
CCD-Extra-Variable.sh
bin/.DS_Store
bin/ccd-import-definition copy.sh
bin/env_variables_all_modded.txt
bin/utils/idam-user-token-temp.sh
bin1/

no changes added to commit (use "git add" and/or "git commit -a")
UK-C02FXE9CMD6M:ccd-docker dineshpatel$ git checkout easy_setup
error: pathspec easy_setup did not match any file(s) known to git
UK-C02FXE9CMD6M:ccd-docker dineshpatel$ git fetch
remote: Enumerating objects: 373, done.
remote: Counting objects: 100% (373/373), done.
remote: Compressing objects: 100% (191/191), done.
remote: Total 373 (delta 249), reused 282 (delta 182), pack-reused 0
Receiving objects: 100% (373/373), 1001.71 KiB | 2.51 MiB/s, done.
Resolving deltas: 100% (249/249), completed with 18 local objects.
From github.com:hmcts/ccd-docker
   3c0a375..e345af4  master               -> origin/master
 * [new branch]      CCD-3349_Proxy-Fix   -> origin/CCD-3349_Proxy-Fix
 * [new branch]      CCD-3573             -> origin/CCD-3573
   531e872..2b48ed6  RDM-12741            -> origin/RDM-12741
 * [new branch]      RDM-12851            -> origin/RDM-12851
 * [new branch]      RDM-12872---xui_webapp-client-id-env-variable-for-use-by-Befta-tests -> origin/RDM-12872---xui_webapp-client-id-env-variable-for-use-by-Befta-tests
 * [new branch]      RDM-13213            -> origin/RDM-13213
 * [new branch]      WLTS-31              -> origin/WLTS-31
 * [new branch]      access-control-users -> origin/access-control-users
 * [new branch]      add-hmc              -> origin/add-hmc
 * [new branch]      corrections          -> origin/corrections
 * [new branch]      danlysiak-patch-1    -> origin/danlysiak-patch-1
 * [new branch]      lau-case-disposer    -> origin/lau-case-disposer
UK-C02FXE9CMD6M:ccd-docker dineshpatel$ git checkout easy_setup
error: pathspec easy_setup did not match any file(s) known to git
UK-C02FXE9CMD6M:ccd-docker dineshpatel$ cd ..
UK-C02FXE9CMD6M:CCD_Projects dineshpatel$ cd ts-translation-service/
UK-C02FXE9CMD6M:ts-translation-service dineshpatel$ git status
On branch master
Your branch is up to date with origin/master.

nothing to commit, working tree clean
UK-C02FXE9CMD6M:ts-translation-service dineshpatel$ cls

UK-C02FXE9CMD6M:ts-translation-service dineshpatel$ git pull origin master --rebase
remote: Enumerating objects: 577, done.
remote: Counting objects: 100% (577/577), done.
remote: Compressing objects: 100% (182/182), done.
remote: Total 577 (delta 199), reused 553 (delta 184), pack-reused 0
Receiving objects: 100% (577/577), 80.85 KiB | 1.80 MiB/s, done.
Resolving deltas: 100% (199/199), completed with 23 local objects.
From https://github.com/hmcts/ts-translation-service
 * branch            master     -> FETCH_HEAD
   60bf5a7..f2a050a  master     -> origin/master
Updating 60bf5a7..f2a050a
Fast-forward
 Jenkinsfile_CNP                                                                  |   4 +-
 build.gradle                                                                     |  11 +-
 charts/ts-translation-service/Chart.yaml                                         |   6 +-
 charts/ts-translation-service/values.yaml                                        |   2 +
 config/owasp/suppressions.xml                                                    |  13 +++
 .../uk/gov/hmcts/reform/translate/TranslationServiceTestAutomationAdapter.java   |  28 ++---
 .../{GetTranslationsEvaluator.java => ContainsTestTranslationsEvaluator.java}    |   6 +-
 .../java/uk/gov/hmcts/reform/translate/customvalue/CustomValueKey.java           |   2 +-
 src/functionalTest/resources/features/F-002 - Put Dictionary/F-002.feature       |  68 +++++++++++
 src/functionalTest/resources/features/F-002 - Put Dictionary/S-002.14.td.json    |  28 +++++
 src/functionalTest/resources/features/F-002 - Put Dictionary/S-002.15.td.json    |  27 +++++
 src/functionalTest/resources/features/F-002 - Put Dictionary/S-002.16.td.json    |  30 +++++
 src/functionalTest/resources/features/F-002 - Put Dictionary/S-002.17.td.json    |  31 +++++
 src/functionalTest/resources/features/F-002 - Put Dictionary/S-002.18.td.json    |  34 ++++++
 src/functionalTest/resources/features/F-003 - Request Translations/F-003.feature |  36 ++++--
 .../resources/features/F-003 - Request Translations/S-003.1.td.json              |  17 +--
 .../resources/features/F-003 - Request Translations/S-003.2.td.json              |  14 +--
 .../resources/features/F-003 - Request Translations/S-003.3.td.json              |  14 +--
 .../resources/features/F-003 - Request Translations/S-003.4.td.json              |  11 +-
 .../resources/features/F-003 - Request Translations/S-003.5.td.json              |  10 +-
 .../resources/features/F-003 - Request Translations/S-003.6.td.json              |  31 +++++
 .../resources/features/F-003 - Request Translations/S-003.7.td.json              |  32 +++++
 src/functionalTest/resources/features/common/Common_No_Auth_Request.td.json      |   9 ++
 src/functionalTest/resources/features/common/Invalid_Auth_Header.td.json         |   5 +
 src/functionalTest/resources/features/common/No_Invoking_User.td.json            |   6 +
 src/integrationTest/java/uk/gov/hmcts/reform/translate/ApplicationParamsIT.java  |  76 ++++++++++++
 .../java/uk/gov/hmcts/reform/translate/controllers/DictionaryControllerIT.java   | 114 +++++++++++++-----
 src/integrationTest/resources/sql/put-create-Dictionary_EnglishPhrases.sql       |   4 +-
 src/main/java/uk/gov/hmcts/reform/translate/ApplicationParams.java               |   2 -
 src/main/java/uk/gov/hmcts/reform/translate/config/SecurityConfiguration.java    |  15 ++-
 .../reform/translate/security/CustomPermitAllAuthenticationTokenBuilder.java     |  29 +++++
 .../reform/translate/security/HttpServletRequestWithoutAuthenticationHeader.java |  51 ++++++++
 .../uk/gov/hmcts/reform/translate/security/JwtGrantedAuthoritiesConverter.java   |   4 +-
 src/main/java/uk/gov/hmcts/reform/translate/security/SecurityUtils.java          |  45 ++++---
 .../gov/hmcts/reform/translate/security/filter/PutDictionaryEndpointFilter.java  |  61 ++++++++++
 .../uk/gov/hmcts/reform/translate/security/filter/TranslateCyEndpointFilter.java |  44 +++++++
 src/main/java/uk/gov/hmcts/reform/translate/security/filter/package-info.java    |   4 +
 src/main/java/uk/gov/hmcts/reform/translate/service/DictionaryService.java       |  39 +++----
 .../java/uk/gov/hmcts/reform/translate/controllers/DictionaryControllerTest.java |   4 +-
 .../uk/gov/hmcts/reform/translate/errorhandling/RestExceptionHandlerTest.java    |   6 +-
 .../translate/security/HttpServletRequestWithoutAuthenticationHeaderTest.java    | 183 +++++++++++++++++++++++++++++
 .../gov/hmcts/reform/translate/security/JwtGrantedAuthoritiesConverterTest.java  |  25 ++--
 src/test/java/uk/gov/hmcts/reform/translate/security/SecurityUtilsTest.java      | 245 ++++++++++++++++++++++++++++-----------
 .../hmcts/reform/translate/security/filter/PutDictionaryEndpointFilterTest.java  | 117 +++++++++++++++++++
 .../hmcts/reform/translate/security/filter/TranslateCyEndpointFilterTest.java    |  85 ++++++++++++++
 src/test/java/uk/gov/hmcts/reform/translate/service/DictionaryServiceTest.java   | 136 ++++++++++++++--------
 46 files changed, 1466 insertions(+), 298 deletions(-)
 rename src/functionalTest/java/uk/gov/hmcts/reform/translate/customvalue/{GetTranslationsEvaluator.java => ContainsTestTranslationsEvaluator.java} (82%)
 create mode 100644 src/functionalTest/resources/features/F-002 - Put Dictionary/S-002.14.td.json
 create mode 100644 src/functionalTest/resources/features/F-002 - Put Dictionary/S-002.15.td.json
 create mode 100644 src/functionalTest/resources/features/F-002 - Put Dictionary/S-002.16.td.json
 create mode 100644 src/functionalTest/resources/features/F-002 - Put Dictionary/S-002.17.td.json
 create mode 100644 src/functionalTest/resources/features/F-002 - Put Dictionary/S-002.18.td.json
 create mode 100644 src/functionalTest/resources/features/F-003 - Request Translations/S-003.6.td.json
 create mode 100644 src/functionalTest/resources/features/F-003 - Request Translations/S-003.7.td.json
 create mode 100644 src/functionalTest/resources/features/common/Common_No_Auth_Request.td.json
 create mode 100644 src/functionalTest/resources/features/common/Invalid_Auth_Header.td.json
 create mode 100644 src/functionalTest/resources/features/common/No_Invoking_User.td.json
 create mode 100644 src/integrationTest/java/uk/gov/hmcts/reform/translate/ApplicationParamsIT.java
 create mode 100644 src/main/java/uk/gov/hmcts/reform/translate/security/CustomPermitAllAuthenticationTokenBuilder.java
 create mode 100644 src/main/java/uk/gov/hmcts/reform/translate/security/HttpServletRequestWithoutAuthenticationHeader.java
 create mode 100644 src/main/java/uk/gov/hmcts/reform/translate/security/filter/PutDictionaryEndpointFilter.java
 create mode 100644 src/main/java/uk/gov/hmcts/reform/translate/security/filter/TranslateCyEndpointFilter.java
 create mode 100644 src/main/java/uk/gov/hmcts/reform/translate/security/filter/package-info.java
 create mode 100644 src/test/java/uk/gov/hmcts/reform/translate/security/HttpServletRequestWithoutAuthenticationHeaderTest.java
 create mode 100644 src/test/java/uk/gov/hmcts/reform/translate/security/filter/PutDictionaryEndpointFilterTest.java
 create mode 100644 src/test/java/uk/gov/hmcts/reform/translate/security/filter/TranslateCyEndpointFilterTest.java
UK-C02FXE9CMD6M:ts-translation-service dineshpatel$ git fetch -app
error: did you mean `--app` (with two dashes)?
UK-C02FXE9CMD6M:ts-translation-service dineshpatel$ git fetch -ll
error: unknown switch `l